"""
Index and log generation for the wiki.

generate_index: rewrites wiki/index.md with [[wikilinks]] in body (LLM-readable).
append_log:     appends a timestamped entry to wiki/log.md (append-only).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .config import Config
from .state import StateDB
from .vault import atomic_write, parse_note


def generate_index(config: Config, db: StateDB) -> Path:
    """
    Write wiki/index.md — a flat catalogue of concepts, sources, and queries.
    All entries use body [[wikilinks]] so Obsidian graph picks them up.
    Returns the path written.
    """
    now = datetime.now().strftime("%Y-%m-%d")

    # Gather published articles (not drafts, not sources/ or INDEX.md)
    articles = db.list_articles(drafts_only=False)
    published = [a for a in articles if not a.is_draft]

    # Separate concepts from source summaries
    concept_articles = []
    source_articles = []
    for art in published:
        rel = art.path
        if "/sources/" in rel or "\\sources\\" in rel:
            source_articles.append(art)
        else:
            concept_articles.append(art)

    # Also pick up source summary pages directly from wiki/sources/ filesystem
    # (in case they were created outside of DB tracking)
    source_pages: list[tuple[str, str]] = []  # (title, link_text)
    if config.sources_dir.exists():
        for md in sorted(config.sources_dir.glob("*.md")):
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                quality = meta.get("quality", "")
                src_file = meta.get("source_file", "")
                hint = quality if quality else src_file
                source_pages.append((title, hint))
            except Exception:
                source_pages.append((md.stem, ""))

    # Build concept entries from DB
    concept_entries: list[tuple[str, str]] = []
    for art in sorted(concept_articles, key=lambda a: a.title.lower()):
        concept_entries.append((art.title, ""))

    # Also scan wiki/ root for published .md not in DB (safe fallback)
    known_titles = {a.title for a in concept_articles}
    if config.wiki_dir.exists():
        for md in sorted(config.wiki_dir.glob("*.md")):
            if md.name == "index.md" or md.name == "INDEX.md" or md.name == "log.md":
                continue
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                if title not in known_titles:
                    concept_entries.append((title, ""))
                    known_titles.add(title)
            except Exception:
                pass

    # Build index body
    lines = [
        "---",
        "title: Wiki Index",
        "tags: [meta, index]",
        f"updated: {now}",
        "---",
        "",
        "# Wiki Index",
        "",
    ]

    if concept_entries:
        lines.append("## Concepts")
        for title, hint in concept_entries:
            entry = f"- [[{title}]]"
            if hint:
                entry += f" — {hint}"
            lines.append(entry)
        lines.append("")

    if source_pages:
        lines.append("## Sources")
        for title, hint in source_pages:
            entry = f"- [[{title}]]"
            if hint:
                entry += f" — {hint}"
            lines.append(entry)
        lines.append("")

    total = len(concept_entries) + len(source_pages)
    lines.append(f"_Auto-generated by olw. {total} entries._")

    index_path = config.wiki_dir / "index.md"
    atomic_write(index_path, "\n".join(lines) + "\n")
    return index_path


def append_log(config: Config, entry: str) -> Path:
    """
    Append a timestamped entry to wiki/log.md (append-only).
    Creates log.md with header if it doesn't exist.
    Returns the path.
    """
    log_path = config.wiki_dir / "log.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    if not log_path.exists():
        header = "---\ntitle: Operation Log\ntags: [meta]\n---\n\n# Operation Log\n\n"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        log_path.write_text(header, encoding="utf-8")

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"\n## [{now}] {entry}\n")

    return log_path
